"use client";
import React from "react";
import { Button } from "@/components/ui/button";
import { Download } from "lucide-react";

const DownloadSummaryButton = ({
  file_name,
  title,
  summaryText,
  createdAt,
}: {
  file_name: string;
  title: string;
  summaryText: string;
  createdAt: string;
}) => {
  const handleDownload = () => {
    const summaryContent = `# ${title}
    Generated Summary
    Generated on:${new Date(createdAt).toLocaleDateString()}
    
    ${summaryText}
    
    Original File: ${file_name}
    Generated by Summuro`;

    const blob = new Blob([summaryContent], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `Summary-${title.replace(/[^a-z0-9]/gi, "_")}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };
  return (
    <Button
      size={"sm"}
      className="h-8 px-3 bg-emerald-100 text-emerald-600 hover:text-emerald-700 hover:bg-emerald-50"
      onClick={handleDownload}
    >
      <Download className="h-4 w-4 mr-1" />
      Download Summary
    </Button>
  );
};

export default DownloadSummaryButton;
